version: "3"
services:
  mongodb:
    image: "mongo"
    volumes:
      - data:/data/db
    # environment:
      # MONGO_INITDB_ROOT_USERNAME: admin
      # MONGO_INITDB_ROOT_PASSWORD: root
    env_file:
      - ./.env
  backend:
    build: ./backend
    ports:
      # HOST:CONTAINER
      - "3080:80"
    volumes:
      - logs:/app/logs
      - ./backend/:/app
      - /app/node_modules
    env_file:
      - ./.env
    depends_on:
      - mongodb
  # frontend:
  #   build: ./frontend
  #   ports:
  #     - "4000:3000"
  #   volumes:
  #     - ./frontend/src:/app/src
  #   stdin_open: true
  #   tty: true
  #   depends_on:
  #     - backend
volumes:
  data:
  logs: