# Generated by Django 5.0.3 on 2024-03-25 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('chair_no', models.IntegerField(blank=True, null=True, verbose_name='Number of chairs')),
                ('employee_no', models.IntegerField(blank=True, null=True, verbose_name='Number of employees')),
            ],
        ),
        migrations.CreateModel(
            name='ItemModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('item_type', models.CharField(choices=[(0, 'Optical equipment'), (1, 'Microcontrollers'), (2, 'Software equipment')], default='Optical equipment', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
